# Generated by Django 3.2.6 on 2021-08-06 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Super_AdminAccount',
            fields=[
                ('SId', models.AutoField(primary_key=True, serialize=False)),
                ('Fname', models.CharField(default='First Name', max_length=255)),
                ('Lname', models.CharField(default='Last Name', max_length=255)),
                ('Email', models.EmailField(default='Email Name', max_length=255)),
                ('Password', models.TextField(default='Password ', max_length=3000)),
                ('ContactNo', models.CharField(default='Contact no', max_length=100)),
                ('Profile', models.ImageField(default='SuperAdmin/dummy.jpg', upload_to='SuperAdmin/')),
            ],
        ),
    ]
