# Generated by Django 3.2.6 on 2021-08-06 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Items_Name', models.CharField(default='', max_length=255)),
                ('Stock', models.IntegerField(default=0)),
                ('Product_Status', models.CharField(default='True', max_length=10)),
                ('Category_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.category')),
            ],
        ),
    ]
