# Generated by Django 3.2.6 on 2021-08-07 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='Date_Time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
