# Generated by Django 3.2.6 on 2021-08-29 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_items_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='Description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='items',
            name='Price',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='subCategory',
            fields=[
                ('sub_Category_Id', models.AutoField(primary_key=True, serialize=False)),
                ('sub_Category_name', models.CharField(default='', max_length=200)),
                ('Category_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.category')),
            ],
        ),
    ]
