# Generated by Django 3.2.6 on 2021-08-29 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20210829_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='sub_Category_Id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.subcategory'),
        ),
    ]
