# Generated by Django 3.2.6 on 2021-08-29 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_items_sub_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='productimg',
            field=models.ImageField(default='product/dummy.jpg', upload_to='product/'),
        ),
    ]
