# Generated by Django 3.2.6 on 2021-09-08 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_items_productimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandname', models.CharField(default='', max_length=200)),
                ('brandlogo', models.ImageField(default='product/dummy.jpg', upload_to='brand/')),
                ('Category_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.category')),
            ],
        ),
    ]
