# Generated by Django 3.2.6 on 2021-09-08 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brandname',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
    ]
