# Generated by Django 3.2.6 on 2021-09-09 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_alter_subcategory_sub_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='brandid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.brand'),
        ),
    ]
