# Generated by Django 3.2.6 on 2021-09-12 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_customerorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(default='', max_length=255)),
                ('Password', models.TextField(default='', max_length=3000)),
                ('Registration_Date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
