# Generated by Django 3.2.6 on 2021-09-12 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_customerorder_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerorder',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='customerorder',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('processing', 'processing'), ('done', 'done')], default='pending', max_length=20),
        ),
    ]
