# Generated by Django 3.2.6 on 2021-09-12 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_auto_20210912_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
